### PR TITLE
Final Changes - Blog Posts Appended

### PR DESCRIPTION
**Pull request by sapierre26**
## Developer: Sanaia Pierre

Closes #{ISSUE NUMBER HERE}

### Pull Request Summary

I have appended 3 blog posts into the div container on the blog.html page. I created a typescript file and within that defined a function, itOverBlog(). This function identifies the div container and appends the blog posts from the Type I made to the container labeled with the specified id. 

### Pull Request Checklist

- [ ] Code is neat, readable, and works
- [ ] Comments are appropriate
- [ ] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [ ] The developer name is specified
- [ ] The summary is completed
- [ ] Ask for a review in communication channels

### CODE REVIEW

**Comment by javalosr2004** [comment]
Hi Sanaia, your missing one of the requirements for this milestone, which is that when the user clicks on one of the containers / links, it should take them to the actual blog.

**Comment by sapierre26** [comment]
> Hi Sanaia, your missing one of the requirements for this milestone, which is that when the user clicks on one of the containers / links, it should take them to the actual blog.

Hi! Are you referring to when a person clicks on one of the navigation links? It should take them to that blog page?

**Comment by sapierre26** [comment]
This is my initial submission. I want to work on it some more before the final final submission.

**Comment by jlaksana** [comment]
Marking this complete. You can fix this issue in your milestone 2

**Pull request closed without merging**
