### PR TITLE
Sophia Peckner - Milestone 1/2/3A/3B/4

### PR DESCRIPTION
**Pull request by sophiapeckner**
## Developer: Sophia Peckner

Closes #{168}

### Pull Request Summary

Finished Milestone 4. Had trouble posting comments--I could set fields but couldn't seem to push into an array. Glad to have learned how to create Components and Dynamic App Routers. 

### Pull Request Checklist

- [ ] Code is neat, readable, and works
- [ ] Comments are appropriate
- [ ] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [ ] The developer name is specified
- [ ] The summary is completed
- [ ] Ask for a review in communication channels

### Screenshots/Screencast
milestone1
milestone3a
milestone3b
milestone4_A
milestone4_B

### CODE REVIEW

**Comment by javalosr2004** [comment]
Hi Sophia! Can you please post your link and if you are still encountering issues in regards to pushing comments, take a look at #cp-bootcamp-help on Slack, I believe there were a couple people facing a similar issue, but they have resolved it.

**Comment by sophiapeckner** [comment]
Screenshot 2023-12-31 at 2 23 32 PM
Whenever I deploy I get a 404 error (attached). Sources online recommend to add a vercel.json file, however this error still occurs. Do you have any ideas on what could be causing this error?

**Comment by javalosr2004** [comment]
Missing comments forms :( , I will let not having a portfolio slide, but learning how to implement client -> server functions is incredibly important. Let me know once that is completed, as to remove the asterick!

**Review by oli-lane — COMMENTED** [review]
Nice work! Looks good

**Pull request closed without merging**
